name: Run security Scan

on:
  schedule:
    - cron: '0 2 * * *'  # Exécution quotidienne à 2h du matin UTC
  pull_request:
    branches:
      - main

jobs:
  security_gate:
    uses: naouaichRepo/all-reusables-workflows/.github/workflows/security-reusable-gate.yml@v1
    