name: Security SCA scan

on:
  pull_request:
    branches:
      - main
      - develop
      - preprod

jobs:
  trivy: 
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read
    
    steps:
      - name: üß™ List files 1
        run: ls -la

      - name: üì• Checkout du code
        uses: actions/checkout@v4

      - name: üß™ List files 2
        run: ls -la

      - name: üì¶ Install trivy
        run: brew install trivy
      
      - name: üÜî Generate unique and random string for unique file naming
        run: echo "UNIQ_STR=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 30)" >> "$GITHUB_ENV"

      - name: Run Trivy for scan high vulnerabilities levels and add severity result in report
        run: |
          trivy fs --scanners vuln,secret,config . --format sarif --output output-${UNIQ_STR}.json
      
      - name: üîÑ Count and store vuln
        run: |
          jq '.runs[0].results | length' output-${UNIQ_STR}.json > vuln_count.txt
          VULN_COUNT=$(cat ./vuln_count.txt)
          echo "Nombre de vuln√©rabilit√©s d√©tect√©es : $VULN_COUNT"
          echo "VULN_COUNT=$VULN_COUNT" >> $GITHUB_ENV

      - name: ‚úÖ V√©rification du r√©sultat de l‚Äôanalyse
        run: |
          if [ "${VULN_COUNT}" -gt 0 ]; then
            echo "‚ùå ${VULN_COUNT} vuln√©rabilit√©s d√©tect√©es. CI bloqu√©e."
            exit 1
          else
            echo "‚úÖ Aucune vuln√©rabilit√© d√©tect√©e. CI valid√©e."
          fi